### ISSUE TITLE
Python 3.11 Support

### ISSUE THREAD

**Issue by brianwawok** [hzdg/django-enumfields#133]
Looks like some tweaks are going to be needed to work in Python 3.11?

https://docs.python.org/3/whatsnew/3.11.html#enum

  File "/python3.11/site-packages/enumfields/enums.py", line 17, in __new__
    attrs._member_names.remove('Labels')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'remove'

**Comment by akx** [comment]
My fork https://github.com/akx/django-enumfields2 (https://pypi.org/project/django-enumfields2) is compatible with Python 3.11. It's a drop-in replacement, so just `pip uninstall django-enumfields` and `pip install django-enumfields2`.
